apiVersion: apps/v1
kind: Deployment
metadata:
  name: chirpstack-bridge
  namespace: default
  labels:
    app: chirpstack-bridge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chirpstack-bridge
  template:
    metadata:
      labels:
        app: chirpstack-bridge
    spec:
      imagePullSecrets:
        - name: registry-rriv
      containers:
        - name: chirpstack-bridge
          image: registry.digitalocean.com/rriv/chirpstack-bridge:latest
          ports:
            - containerPort: 1883
